server:  
  port: 8080  
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  
# spring:  
#   datasource:  //数据库配置
#     url : jdbc:mysql://localhost:3306/newbirds  
#     username : root  
#     password : mymysql  
#     driverClassName : com.mysql.jdbc.Driver  
